name: Re-build Doc Site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Update Documentation Site
    runs-on: ubuntu-latest
    # Set some sort of timeout in the event of run-away builds.  We are limited on concurrent jobs so, get rid of them.
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: Update Gallery Links
      #   run: python ./.github/scripts/update-gallery.py

      - name: Update Site
        run: |
          npm ci
          npm run build
          rm -fr ./docs/*
          cp -r ./build/* ./docs/

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          author_name: 'OpenGOALBot'
          author_email: 'OpenGOALBot@users.noreply.github.com'
          message: "Updated github pages site"
